# Generated by Django 4.2.3 on 2024-07-07 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userId",
            field=models.CharField(default=uuid.uuid4, max_length=225, unique=True),
        ),
    ]
